
CREATE TABLE PUBLISHER (
		PUBLISHER_ID VARCHAR2(10) NOT NULL,
		NAME VARCHAR2(50),
		ADDRESS VARCHAR2(100),
		EMAIL_ID VARCHAR2(100) NOT NULL,
		WEB_ADDRESS VARCHAR2(100),
		PRIMARY KEY (PUBLISHER_ID)
);

CREATE TABLE BOOK(
		ISBN                        VARCHAR2(20) NOT NULL,
		TITLE                       VARCHAR2(100) NOT NULL,
		COVER_IMAGE                 VARCHAR2(100),
		BINDING                     VARCHAR2(100),
		NUMBER_OF_PAGES             NUMBER(5,0),
		ORIGINAL_PUBLICATION_YEAR   NUMBER(5,0),
		LANGUAGE                    VARCHAR2(10),
		DESCRIPTION                 VARCHAR2(2000),
		SUMMARY                     VARCHAR2(2000),
		PUBLISHER_ID                VARCHAR2(10),
		PUBLICATION_DATE            DATE,
		PRIMARY KEY (ISBN),
		FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER
);

CREATE TABLE BOOK_AWARD (
		ISBN				VARCHAR2(20) NOT NULL,
		AWARDS			VARCHAR2(500) NOT NULL,		
		PRIMARY KEY (ISBN, AWARDS),
		FOREIGN KEY (ISBN) REFERENCES BOOK
);

CREATE TABLE PERSON (
		PERSON_ID			VARCHAR2(10) NOT NULL,
		FIRST_NAME		VARCHAR2(20) NOT NULL,
		LAST_NAME			VARCHAR2(20) NOT NULL,
		ADDRESS				VARCHAR2(100),
		EMAIL					VARCHAR2(100) NOT NULL,
		PHONE_NUMBER 	VARCHAR2(14),
		DETAILS				VARCHAR2(1000),		
		PRIMARY KEY (PERSON_ID)
);

CREATE TABLE AUTHOR (
		PERSON_ID						VARCHAR2(10) NOT NULL,
		WEB_ADDRESS					VARCHAR2(100),		
		PRIMARY KEY (PERSON_ID),
		FOREIGN KEY (PERSON_ID) REFERENCES PERSON
);

CREATE TABLE "USER" (
		PERSON_ID						VARCHAR2(10) NOT NULL,
		USER_NAME						VARCHAR2(20) NOT NULL,
		PASSWORD						VARCHAR2(200) NOT NULL,		
		PRIMARY KEY (PERSON_ID),
		FOREIGN KEY (PERSON_ID) REFERENCES PERSON
);

CREATE TABLE ADMIN (
		PERSON_ID						VARCHAR2(10)  NOT NULL,
		ADMIN_NAME					VARCHAR2(20)  NOT NULL,
		PASSWORD						VARCHAR2(200)  NOT NULL,		
		PRIMARY KEY (PERSON_ID),
		FOREIGN KEY (PERSON_ID) REFERENCES PERSON
);

CREATE TABLE GENRE (
		GENRE_ID				VARCHAR2(10) NOT NULL,
		GENRE_NAME			VARCHAR2(100) NOT NULL,		
		PRIMARY KEY (GENRE_ID)
);

CREATE TABLE BOOK_GENRE (
		ISBN						VARCHAR2(20) NOT NULL,
		GENRE_ID				VARCHAR2(10),		
		PRIMARY KEY (ISBN, GENRE_ID),
		FOREIGN KEY (ISBN) REFERENCES BOOK,
		FOREIGN KEY (GENRE_ID) REFERENCES GENRE
);

CREATE TABLE WRITTEN_BY (
		ISBN				VARCHAR2(20) NOT NULL,
		PERSON_ID		VARCHAR2(10) NOT NULL,			
		PRIMARY KEY (ISBN, PERSON_ID),
		FOREIGN KEY (ISBN) REFERENCES BOOK,
		FOREIGN KEY (PERSON_ID) REFERENCES AUTHOR
);

CREATE TABLE BOOKSHELF (
		BOOKSHELF_ID		VARCHAR2(100) NOT NULL,
		PERSON_ID				VARCHAR2(10)  NOT NULL,
		BOOKSHELF_NAME  VARCHAR2(50),		
		PRIMARY KEY (BOOKSHELF_ID),
		FOREIGN KEY (PERSON_ID) REFERENCES "USER"
);

CREATE TABLE BOOKSHELF_CONTENT (
		BOOKSHELF_ID		VARCHAR2(10) NOT NULL,
		ISBN						VARCHAR2(20) NOT NULL,	
		PRIMARY KEY (BOOKSHELF_ID, ISBN),
		FOREIGN KEY (ISBN) REFERENCES BOOK,
		FOREIGN KEY (BOOKSHELF_ID) REFERENCES BOOKSHELF
);

CREATE TABLE RATING (
		ISBN					VARCHAR2(20) NOT NULL,
		PERSON_ID			VARCHAR2(10) NOT NULL,
		VALUE					NUMBER(1),
		RATING_DATE		DATE,		
		PRIMARY KEY (ISBN, PERSON_ID),
		FOREIGN KEY (ISBN) REFERENCES BOOK,
		FOREIGN KEY (PERSON_ID) REFERENCES "USER"
);

CREATE TABLE REVIEW ( 
		REVIEW_ID				VARCHAR2(10) NOT NULL,
		ISBN 						VARCHAR2(20) NOT NULL,
		PERSON_ID				VARCHAR2(10) NOT NULL,
		REVIEW_CONTENT	VARCHAR2(2000),
		REVIEW_DATE 		DATE,		
		PRIMARY KEY (REVIEW_ID, ISBN, PERSON_ID),
		FOREIGN KEY (ISBN) REFERENCES BOOK,
		FOREIGN KEY (PERSON_ID) REFERENCES "USER"
);


